urls.py
from django.urls import path

from . import views
app_name = 'contact_book'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.new_contact, name='new_contact'),
    path('submit-form',views.submit_contact, name='submit_contact'),
    path('upload/', views.image_upload_view),
    path('delete_contact/<int:id>', views.delete_contact, name='delete_contact'),
    path('detail/<int:id>', views.detail_contact, name='detail_contact'),
    path('edit/<int:id>', views.edit_contact, name='edit_contact'),
]

models.py
from django.db import models
from django import forms


class contact_details(models.Model):
    name = models.CharField(max_length=200)
    profile= models.ImageField(upload_to='images/',null=True, blank=True)
    mobile_no = models.IntegerField()
    address= models.TextField(max_length=400)
    email= models.CharField(max_length=500)

forms.py
from django import forms 
from .models import *
  
class ContactDetailForm(forms.ModelForm): 
  
    class Meta: 
        model = contact_details
        fields = ['name', 'profile','mobile_no','address','email'];

views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import *
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import contact_details
from django.core.mail import BadHeaderError, send_mail


def new_contact( request):
	if request.method == 'POST': 
		form = ContactDetailForm(request.POST, request.FILES) 
		if form.is_valid(): 
			form.save()
			return redirect('contact_book:index')
	else: 
		form = ContactDetailForm() 
	return render(request, 'contact_book/add.html', {'form' : form})

def index(request):
	latest_contact_list = contact_details.objects.order_by('-id')[:5]
	context = {'latest_contact_list': latest_contact_list}
	return render(request, 'contact_book/index.html', context)

def submit_contact(request):
	if request.method =='POST':
		profile = ContactDetailForm(request.POST, request.FILES)
		if profile.is_valid(): 
			profile.save() 
			return redirect('success') 
		return HttpResponseRedirect('contact_book/index.html')

def image_upload_view(request):
    if request.method == 'POST':
        profile = ContactDetailForm(request.POST, request.FILES)
        if profile.is_valid(): 
            profile.save() 
            return redirect('success') 
    else: 
        profile = ContactDetailForm() 
    return render(request, 'index.html', {'profile' : profile}) 


def edit_contact(request,id):
	if request.method =='POST':
		selected=contact_details.objects.get(id=id)
		profile = ContactDetailForm(request.POST, instance = selected)
		if profile.is_valid(): 
			profile.save() 
			return redirect('contact_book:index') 
	else:
		selected=contact_details.objects.get(id=id)
		profile = ContactDetailForm(instance=selected)
	return render(request, 'contact_book/edit.html',{'profile':profile})


def delete_contact(request,id):
	contact= contact_details.objects.get(id=id)
	if request.method == 'POST':
		contact.delete()
		return redirect('contact_book:index')
	else:
		messages.error(request,"Something Went Wrong")

def detail_contact(request,id):
	selected=contact_details.objects.get(id=id)
	return render(request, 'contact_book/detail.html',{'contacts':selected})

templates/contact_book/add.html
{% extends './layouts.html' %}
<!DOCTYPE html>
<html>
{% block content %}
<body style="background: lightgrey;">
  <div class="container mb-4 mt-4">
    <div class="row justify-content-center">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-head bg-primary text-white p-3">
            <h3 class="text-center container text-uppercase font-weight-bold"> Add Contact</h3>
            
          </div>
          <div class="card-body p-4">
            <form method="POST" enctype="multipart/form-data">
              
              {% csrf_token %}
              {{ form.as_p }}
              <div class="form-group row justify-content-center pt-4" >
                <div class="col-sm-6">
                  <button type="submit" class="btn btn-block btn-primary">Submit</button>
                </div>
              </div>
            </form>
            
            
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}
</html>

templates/contact_book/detail.html
{% extends './layouts.html' %}
<style type="text/css">
	.card {
        margin: 0 auto; 
        float: none; 
        margin-bottom: 10px; 
}
</style>
{% block content %}

<div class="row">
	<div class="col-sm-4"></div>
	<div class="col-sm-4 mt-4">
	<div class="card" style="width: 30rem;height: 60vh;background-color: lightgreen">
	  <div class="card-body">
	  	{% if contacts %}
		<div class="text-center">
			<img src="{{ contacts.profile.url }}" class="img rounded-circle" width="120" height="120">
		</div>
	  	<div class="mt-5 text-left">
	  		<div class="row">
	  			<div class="col"> Name:</div>	  			
	  			<div class="col"> {{ contacts.name }} </div>	  			
	  		</div>
	  		<div class="row">
	  			<div class="col"> Mobile No:</div>	  			
	  			<div class="col"> {{ contacts.mobile_no }} </div>	  			
	  		</div>
	  		<div class="row">
	  			<div class="col"> Email:</div>	  			
	  			<div class="col"> {{ contacts.email }} </div>	  			
	  		</div>
	  		<div class="row">
	  			<div class="col"> Address:</div>	  			
	  			<div class="col"> {{ contacts.address }} </div>	  			
	  		</div>
		</div>
		{% else %}
			<h4>No Data</h4>
		{% endif %}
	  </div>

	</div>
	</div>
	<div class="col-sm-4"></div>
</div>
{% endblock %}

templates/contact_book/edit.html
{% extends './layouts.html' %}
<!DOCTYPE html>
<html>
{% block content %}
<body style="background: lightgrey;">
  <div class="container mb-4 mt-4">
    <div class="row justify-content-center">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-head bg-primary text-white p-3">
            <h3 class="text-center container text-uppercase font-weight-bold"> Edit Section</h3>
            
          </div>
          <div class="card-body p-4">
            <form method="POST" enctype="multipart/form-data">

              {% csrf_token %}
              {{ profile.as_p }}
              <div class="form-group row justify-content-center pt-4" >
                <div class="col-sm-6">
                  <button type="submit" class="btn btn-block btn-primary">Submit</button>
                </div>
              </div>
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}
</html>

templates/contact_book/index.html
{% extends './layouts.html' %}
{% load static from static %}
{% block content %}
{% block header %}
  <header class="masthead" style="background-image:url({% static 'contact_book/img/index.jpg' %});width: 100%;height: 75vh;margin-bottom: 25px">
  	<h1 style="padding-top:15%;text-align: center; color: white;font-size: 65px;text-shadow:blue;text-shadow: 4px 4px #FF0000"><b>Best Code Creator</b></h1>
  </header>
{% endblock %}

<h1 class="text-center container mb-4" style="color:blue"><b> Contact Book</b> <a href="/contact_book/add" class="btn btn-primary float-right">New Contact</a></h1>
{% if latest_contact_list %}
<table class="table table-hover container">
		<thead>
			<tr>
				<th>Profile</th>
				<th>Name</th>
				<th>Mobile No</th>
				<th>Address</th>
				<th>Email</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for contact in latest_contact_list%}
			<tr>
				<td>
					{% if contact.profile %}
						<img src="{{ contact.profile.url }}" width="40" height="40">
					{% endif %}
					
				</td>
				<td>{{ contact.name }}</td>
				<td>{{ contact.mobile_no}}</td>
				<td>{{ contact.address }}</td>
				<td>{{ contact.email }}</td>
				<td>
					<a class="btn btn-info" href="{% url 'contact_book:detail_contact' contact.id %}">View</a>
				</td>
				<td>
					<a class="btn btn-primary" href="{% url 'contact_book:edit_contact' contact.id %}" role="button">Edit</a>
				</td>
			    <td class="float-right">
				<form class="flex-container" method="POST" action="{% url 'contact_book:delete_contact' contact.id %}" > 
	              {% csrf_token %}
	              <div class="input-group"> 
	                <input type="hidden" name="contact_id" value="{{ contact.id }}">
	                <button name="delete" type="submit" class="btn btn-danger">Delete </button>
	              </div> 
	            </form>
				<td>
			</tr>
			{% endfor %}
			</tbody>
	</table>
	{% else %}
	<p>No Contact List</p>
{% endif %}

{% endblock %}

templates/contact_book/layouts.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title> Contact Book </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <style>
    .fa {
      padding: 5px;
      font-size: 25px;
      width: 50px;
    }
  </style>
</head>
<body>


  <nav class="navbar navbar bg-primary navbar-dark">
    <a class="navbar-brand" href="/contact_book"> Contact </a>
  </nav>

  
<div style="min-height: 68vh">
  {% block content %}
  {% endblock %}
</div>
<div>
<footer style="background-color:gray;height: 20vh">
  <div class="text-center">
    <h3 class="pt-4"><b>Best Code Creator</b></h3>
    <div>
           <a href="https://www.facebook.com/bestcodecreator" class="icoFacebook text-white" title="Facebook"><i class="fa fa-facebook"></i></a>
           <a href="https://www.linkedin.com/in/ashish-yadav-57ba071ba/" class="icoLinkedin text-white" title="Linkedin"><i class="fa fa-linkedin"></i></a>
           <a href="https://twitter.com/BestCodeCreator" class="icoTwitter text-white" title="Twitter"><i class="fa fa-twitter"></i></a>
           <a href="https://www.youtube.com/channel/UCbttfo0hC_MqHkcKFmF05kg" class="icoYoutube text-white" title="Youtube"><i class="fa fa-youtube"></i></a>
    </div>
    <h6>Created by @bestcodecreator</h6>
  </div>
</footer>
</div>
</body>
</html>